### ISSUE TITLE
[Bug] Box Scores Changelog opens up every time I reopen Chrome

### ISSUE THREAD

**Issue by humachine** [mingchia-andy-liu/chrome-extension-nba#20]
Not a big deal, but the Box Scores Changelog opens up every time I reopen Chrome.

**Comment by mingchia-andy-liu** [comment]
This shouldn't happen, it should only open the changelog every time there is a version change or on installed. Can you tell me how you _reopen_ the chrome?

**Comment by humachine** [comment]
@mingchia-andy-liu  - It happens every time I (Command-Q) quit the browser and reopen Google Chrome. OneTab & BoxScores open up a tab each time.

**Comment by mingchia-andy-liu** [comment]
### Can you Describe your environment
  * OS:
  * Chrome version: 
  * Extension version: 

Do you have any extension that might reloads every other extension on start up? 
I have changed the code since then, and haven't been reproduce the bug. I am also on a Mac(High Sierra) with the latest chrome and cannot seem to trigger the issue. Does uninstall and re-intstalling the extension help?
